services:
  - docker

language: generic

before_install:
  - docker build -t arnelplim/github-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arnelplim/github-react npm run test -- --coverage
